var BOOKS=[
{id:1,t:"G'ulom Zafariy",a:"Olim Usmonov"},
{id:2,t:"Munavvar Abdurashidxonov",a:"Sotimjon Holboyev"},
{id:3,t:"Is'hoqxon to'ra Ibrat",a:"Ulug'bek Dolimov"},
{id:4,t:"Abdurauf Fitrat",a:"Bahodir Karimov"},
{id:5,t:"Abdulla Qodiriy",a:"Bahodir Karimov"},
{id:6,t:"Abdulla Avloniy",a:"Olim Oltinbek"},
{id:7,t:"Abdulhamid Cho'lpon",a:"Dilmurod Quronov"},
{id:8,t:"Mahmudxo'ja Behbudiy",a:"Zaynobiddin Abdurashidov"},
{id:9,t:"Avlodlar dovoni",a:"Pirimqul Qodirov"},
{id:10,t:"Aqchagul",a:"Murodboy Nizanov"},
{id:11,t:"Alisher Navoiy",a:"Isajon Sulton"},
{id:12,t:"Qiyomat",a:"Chingiz Aytmatov"},
{id:13,t:"Bilga xoqon",a:"Isajon Sulton"},
{id:14,t:"Alpomish dostoni",a:"Xalq og'zaki ijodi"},
{id:15,t:"Tohir va Zuhra dostoni",a:"Xalq og'zaki ijodi"},
{id:16,t:"Ahmad Yassaviyning so'nggi safari",a:"Sa'dulla Siyoyev"},
{id:17,t:"Dashti qipchoq lochini",a:"Sa'dulla Siyoyev"},
{id:18,t:"Baxtli oila",a:"Shayx Muhammad Sodiq Muhammad Yusuf"},
{id:19,t:"Bobo so'z izidan",a:"Eshqobil Shukur"},
{id:20,t:"Boburiynoma",a:"Xayriddin Sultonov"},
{id:21,t:"Ko'ngil ozodadur",a:"Xayriddin Sultonov"},
{id:22,t:"Yozning yolg'iz yodgori",a:"Xayriddin Sultonov"},
{id:23,t:"Odamlardan tinglab hikoya",a:"Xayriddin Sultonov"},
{id:24,t:"Bolalik",a:"Oybek"},
{id:25,t:"Bonu",a:"Iqbol Mirzo"},
{id:26,t:"Bu dunyoda o'lib bo'lmaydi",a:"Tog'ay Murod"},
{id:27,t:"Bug'doybo'y Vatan",a:"Sirojiddin Sayyid"},
{id:28,t:"Buyuk qushlar",a:"Halima Xudoyberdiyeva"},
{id:29,t:"Daftar hoshiyasidagi bitiklar",a:"O'tkir Hoshimov"},
{id:30,t:"Devoni hikmat",a:"Ahmad Yassaviy"},
{id:31,t:"Dunyoning ishlari",a:"O'tkir Hoshimov"},
{id:32,t:"Yolg'iz",a:"Xurshid Do'stmuhammad"},
{id:33,t:"Bozor",a:"Xurshid Do'stmuhammad"},
{id:34,t:"Javzo",a:"Azim Suyun"},
{id:35,t:"Jimjitlik",a:"Said Ahmad"},
{id:36,t:"Zarbulmasal",a:"Gulxaniy"},
{id:37,t:"Iymonlashish umidi",a:"Tohir Malik"},
{id:38,t:"Ikki eshik orasi",a:"O'tkir Hoshimov"},
{id:39,t:"Imom Moturidiy",a:"Luqmon Bo'rixon"},
{id:40,t:"Jaziramadagi odamlar",a:"Luqmon Bo'rixon"},
{id:41,t:"Ichindagi ichindadir",a:"Jaloliddin Rumiy"},
{id:42,t:"Kafansiz ko'milganlar",a:"Shukrullo"},
{id:43,t:"Kecha va kunduz",a:"Abdulhamid Cho'lpon"},
{id:44,t:"Qobusnoma",a:"Kaykovus"},
{id:45,t:"Qora quyun",a:"Normurod Norqobilov"},
{id:46,t:"Qo'shchinor chiroqlari",a:"Abdulla Qahhor"},
{id:47,t:"Maymun yetaklagan odam",a:"Nazar Eshonqul"},
{id:48,t:"Urush odamlari",a:"Nazar Eshonqul"},
{id:49,t:"Mantiqut tayr",a:"Farididdin Attor"},
{id:50,t:"Masnaviy ma'naviy",a:"Jaloliddin Rumiy"},
{id:51,t:"Mashaqqatlar osha yulduzlar sari",a:"Abduqayum Yo'ldoshev"},
{id:52,t:"Osmon og'ushi",a:"Abduqayum Yo'ldoshev"},
{id:53,t:"Mehrobdan chayon",a:"Abdulla Qodiriy"},
{id:54,t:"Muvozanat",a:"Ulug'bek Hamdam"},
{id:55,t:"Navoiy",a:"Oybek"},
{id:56,t:"Nur borki, zulmat bor",a:"O'tkir Hoshimov"},
{id:57,t:"Bahor qaytmaydi",a:"O'tkir Hoshimov"},
{id:58,t:"Ov",a:"Tohir Malik"},
{id:59,t:"Odamiylik mulki",a:"Tohir Malik"},
{id:60,t:"Oydinda yurgan odamlar",a:"Tog'ay Murod"},
{id:61,t:"Oltin zanglamas",a:"Shuhrat"},
{id:62,t:"Ot kishnagan oqshom",a:"Tog'ay Murod"},
{id:63,t:"Ota izidan",a:"Odil Yoqubov"},
{id:64,t:"Otamdan qolgan dalalar",a:"Tog'ay Murod"},
{id:65,t:"Sevgi qissalari",a:"O'tkir Hoshimov"},
{id:66,t:"So'nggi o'q",a:"Tohir Malik"},
{id:67,t:"Tarixiy qissalar",a:"Mirkarim Osim"},
{id:68,t:"Temur tuzuklari",a:"Sohibqiron Amir Temur"},
{id:69,t:"Turkiy guliston yoxud axloq",a:"Abdulla Avloniy"},
{id:70,t:"Turkiston qayg'usi",a:"Alixonto'ra Sog'uniy"},
{id:71,t:"O'zbegim",a:"Erkin Vohidov"},
{id:72,t:"Ultontoq",a:"Olim Toshboyev"},
{id:73,t:"Ulug'bek xazinasi",a:"Odil Yoqubov"},
{id:74,t:"O'n sakkizga kirmagan kim bor",a:"Shukur Xolmirzayev"},
{id:75,t:"O'tkan kunlar",a:"Abdulla Qodiriy"},
{id:76,t:"Ufq",a:"Said Ahmad"},
{id:77,t:"Fitna - ko'z ilg'amas xatar",a:"Shayx Nuriddin Xoliqnazar"},
{id:78,t:"Fozil odamlar shahri",a:"Forobiy"},
{id:79,t:"Fotima va Zuhra",a:"O'lmas Umarbekov"},
{id:80,t:"Halol nima-yu harom nima",a:"Tohir Malik"},
{id:81,t:"Hind sayyohi",a:"Abdurauf Fitrat"},
{id:82,t:"Chinor",a:"Asqad Muxtor"},
{id:83,t:"Shovqin",a:"Erkin A'zam"},
{id:84,t:"Atoyining tug'ilgan yili",a:"Erkin A'zam"},
{id:85,t:"Anoyining jaydari olmasi",a:"Erkin A'zam"},
{id:86,t:"Shohnoma",a:"Firdavsiy"},
{id:87,t:"Shum bola",a:"G'afur G'ulom"},
{id:88,t:"Sho'rodan qolgan odamlar",a:"Shoyim Bo'tayev"},
{id:89,t:"Erk",a:"Pirimqul Qodirov"},
{id:90,t:"Yulduzlar mangu yonadi",a:"Tog'ay Murod"},
{id:91,t:"Yulduzli tunlar",a:"Pirimqul Qodirov"},
{id:92,t:"Yur, tog'larga ketamiz",a:"Shukur Xolmirzayev"},
{id:93,t:"Jinoyat va jazo",a:"Dostoyevskiy"},
{id:94,t:"Asrga tatigulik kun",a:"Chingiz Aytmatov"},
{id:95,t:"Jamila",a:"Chingiz Aytmatov"},
{id:96,t:"Oq kema",a:"Chingiz Aytmatov"},
{id:97,t:"Men kim sohibqiron Amir Temur",a:"Marsel Brion"},
{id:98,t:"Qutadg'u bilig",a:"Yusuf Xos Hojib"},
{id:99,t:"Jaloliddin Rumiy",a:"Radiy Fish"},
{id:100,t:"Al-kimyogar",a:"Paulo Koelo"}
];

function makeQ(q,o,a){return {q:q,o:o,a:a};}

var TESTS={
1:[
makeQ("1. 'G'ulom Zafariy' asarida kimning hayoti tasvirlanadi?",["Abdulla Qodiriyning","Jadid shoir va dramaturg G'ulom Zafariyning","Munavvar Qorining","Fitratning"],1),
makeQ("2. G'ulom Zafariy qaysi janrda mashhur bo'lgan?",["Roman","Dramaturgiya va she'riyat","Tarixiy qissa","Hikoya"],1),
makeQ("3. Olim Usmonov kimlar haqida yozgan?",["Rus adiblari","Jadid ziyolilari","Sovet davri shoirlari","Qadimgi tarixchilar"],1),
makeQ("4. G'ulom Zafariy qaysi davrda ijod qilgan?",["XIX asr","XX asr boshlari — jadidlik davri","Sovet davrining oxiri","Mustaqillik davri"],1),
makeQ("5. Asar qaysi janrga mansub?",["Roman","Biografik qissa","She'riy to'plam","Dramatik asar"],1),
makeQ("6. G'ulom Zafariyning asosiy g'oyasi nima?",["Boylikka intilish","Milliy uyg'onish va ma'rifat","Harbiy kurash","Diniy targ'ibot"],1),
makeQ("7. Jadidlar harakati qaysi asrda faol bo'lgan?",["XVIII asr","XX asr boshlari","XVI asr","XIX asr o'rtalari"],1),
makeQ("8. G'ulom Zafariy qaysi shahar bilan bog'liq?",["Buxoro","Toshkent","Samarqand","Namangan"],1),
makeQ("9. Asarda jadidlik harakati qanday tasvirlanadi?",["Salbiy","Millatni ma'rifatga chaqiruvchi kuch sifatida","Befarq","Diniy harakat sifatida"],1),
makeQ("10. G'ulom Zafariy nimaga kurashgan?",["Boylik uchun","Ma'rifat va milliy mustaqillik uchun","Harbiy g'alaba uchun","Shaxsiy shuhrat uchun"],1),
makeQ("11. Asardagi eng muhim mavzu nima?",["Sevgi","Jadid ziyolisining hayoti va kurashi","Tabiat tasviri","Sarguzasht"],1),
makeQ("12. G'ulom Zafariy asarlari qaysi tilda yozilgan?",["Fors tilida","O'zbek tilida","Rus tilida","Arab tilida"],1),
makeQ("13. Jadidlar qanday maqsad ko'zlagan?",["Chor Rossiyasiga itoat","Milliy uyg'onish, ta'lim islohoti","Diniy davlat barpo etish","Savdo-sotiqni rivojlantirish"],1),
makeQ("14. Asar uslubi qanday?",["Yumoristik","Biografik-tarixiy","Sarguzasht","Romantik"],1),
makeQ("15. G'ulom Zafariyning fojiasi nimada?",["Kambag'allikda","Sovet tuzumi tomonidan ta'qib va qatl etilganida","Sevgi alamida","Kasallikda"],1),
makeQ("16. Asarda qaysi davr voqealari tasvirlanadi?",["Temuriylar davri","Jadidlik va sovet bosqini davri","Mustaqillik yillari","Chor Rossiyasi hukmronligining boshlanishi"],1),
makeQ("17. G'ulom Zafariy qanday insoniylik namunasi sifatida ko'rsatiladi?",["Manfaatparast","Fidoyi va vatanparvar ziyoli","Qo'rqoq","Diniy fanatik"],1),
makeQ("18. Olim Usmonov bu asarda nima maqsad qilgan?",["Qahramonni tanqid qilish","Unutilgan jadid siymosini xalqqa qaytarish","Ko'ngilni ochish","Tarix darsligini yozish"],1),
makeQ("19. Asar o'zbek adabiyotida qanday ahamiyatga ega?",["Ikkinchi darajali","Jadid adabiyotini tiklash va xotirlashda muhim"],1),
makeQ("20. G'ulom Zafariyning eng mashhur asari qaysi janrda?",["Roman","Dramaturgiya","Qissa","Hikoya"],1)
],
2:[
makeQ("1. 'Munavvar Abdurashidxonov' asari kimning hayotini tasvirlaydi?",["Abdulla Qodiriyning","Munavvar Qori Abdurashidxonov hayotini","Cho'lponning","Fitratning"],1),
makeQ("2. Munavvar Qori qaysi faoliyat bilan mashhur?",["Harbiy sardor","Ma'rifatchi, pedagog va jadid arbobi","Savdogar","Shoir"],1),
makeQ("3. Asar qaysi janrga mansub?",["Detektiv roman","Biografik qissa","She'riy doston","Hajviy asar"],1),
makeQ("4. Munavvar Qori qaysi davr ziyolisi?",["XIX asr o'rtalari","XX asr boshlari — jadidlik davri","Sovet davri oxiri","Mustaqillik davri"],1),
makeQ("5. Asarning asosiy mavzusi nima?",["Sevgi va sadoqat","Ma'rifat, milliy uyg'onish va fidokorlik","Harbiy sarguzasht","Boylik orttirishning yo'llari"],1),
makeQ("6. Munavvar Qori qaysi sohada islohotlar qilgan?",["Harbiy soha","Ta'lim va matbuot sohasida","Savdo sohasida","Qishloq xo'jaligida"],1),
makeQ("7. Sotimjon Holboyev asarida nima maqsad qilgan?",["Qahramonni tanqid qilish","Munavvar Qorining xotirasini tiklash","Ko'ngilni ochish","Siyosiy targ'ibot"],1),
makeQ("8. Munavvar Qorining fojiasi nimada?",["Kambag'allikda","Sovet tuzumi tomonidan qatl etilganida","Sevgi alamida","Kasallikda"],1),
makeQ("9. Asarda jadidlik g'oyasi qanday talqin etiladi?",["Salbiy","Millatni ma'rifatga, mustaqillikka chaqiruvchi harakat sifatida","Diniy harakat","Befarq"],1),
makeQ("10. Munavvar Qori qaysi shahar bilan bog'liq?",["Samarqand","Toshkent","Buxoro","Namangan"],1),
makeQ("11. Asardagi eng kuchli badiiy jihat nima?",["Tabiat tasviri","Qahramon hayoti orqali davr fojiasini aks ettirish","Hajviy sahnalar","Sarguzasht"],1),
makeQ("12. Munavvar Qori qanday insoniylik namunasi?",["Manfaatparast","Fidoyi ma'rifatchi va vatanparvar","Qo'rqoq","Shuhratparast"],1),
makeQ("13. Asarda sovet tuzumiga munosabat qanday?",["Ijobiy","Yashirin tanqid va fojiaviy natija orqali ko'rsatiladi","Befarq","To'g'ridan-to'g'ri maqtov"],1),
makeQ("14. Munavvar Qorining asosiy merosi nima?",["Harbiy g'alaba","Milliy ta'lim va matbuotga qo'shgan hissa","Moddiy boylik","Diplomatik aloqalar"],1),
makeQ("15. Asar uslubi qanday?",["Yumoristik","Tarixiy-biografik, hayotiy va fojiaviy","Fantastik","Romantiк"],1),
makeQ("16. Munavvar Qori qanday qadriyatlar uchun kurashgan?",["Shaxsiy manfaat","Milliy uyg'onish, ta'lim, erkinlik","Diniy hukmronlik","Chor Rossiyasiga itoat"],1),
makeQ("17. Asarda qaysi tarixiy voqealar muhim rol o'ynaydi?",["Temuriylar davri","Jadidlik harakati va sovet bosqini","Ikkinchi Jahon urushi","Mustaqillik yillari"],1),
makeQ("18. Munavvar Qori xalq uchun nima sifatida qoldi?",["Siyosatchi","Milliy ma'naviy yetakchi va o'qituvchi","Harbiy qahramon","Savdogar"],1),
makeQ("19. Asarning o'zbek adabiyotidagi o'rni?",["Oddiy asar","Jadid adabiyotini tiklashga katta hissa qo'shgan muhim asar"],1),
makeQ("20. Asar asosan kimga mo'ljallangan?",["Faqat tarixchilar uchun","Milliy tarixni bilmoqchi bo'lgan barcha o'quvchilar uchun","Faqat bolalar uchun","Faqat ziyolilar uchun"],1)
],
3:[
makeQ("1. 'Is'hoqxon to'ra Ibrat' asari kimning hayotini tasvirlaydi?",["Abdulla Qodiriyning","Is'hoqxon to'ra Ibrat hayotini","Munavvar Qorining","Fitratning"],1),
makeQ("2. Is'hoqxon to'ra Ibrat qaysi faoliyat bilan mashhur?",["Harbiy sardor","Shoir, tarixchi va ma'rifatchi jadid","Savdogar","Diplomat"],1),
makeQ("3. Asar qaysi janrga mansub?",["Detektiv","Biografik qissa","She'riy doston","Hajviy asar"],1),
makeQ("4. Ibrat qaysi shahar bilan bog'liq?",["Toshkent","Namangan","Samarqand","Buxoro"],1),
makeQ("5. Asarning asosiy mavzusi nima?",["Sevgi","Ma'rifat va milliy uyg'onish yo'lidagi kurash","Harbiy sarguzasht","Boylik"],1),
makeQ("6. Ibratning asosiy xizmati nimada?",["Harbiy g'alaba","O'zbek tarixini yozish va milliy ma'rifatni targ'ib qilish","Savdo-sotiq","Diniy islohotlar"],1),
makeQ("7. Ulug'bek Dolimov asarida nima maqsad qilgan?",["Qahramonni tanqid qilish","Is'hoqxon to'ra Ibrat siymosini tiklash","Ko'ngilni ochish","Siyosiy targ'ibot"],1),
makeQ("8. Ibratning fojiasi nimada?",["Kambag'allikda","Sovet tuzumi bosimi ostida ta'qib etilganida","Sevgi alamida","Kasallikda"],1),
makeQ("9. Asarda jadidlik g'oyasi qanday ko'rsatiladi?",["Salbiy","Millatni ma'rifatga chaqiruvchi ulug' harakat sifatida","Diniy harakat","Befarq"],1),
makeQ("10. Ibrat qanday inson sifatida tasvirlanadi?",["Manfaatparast","Ko'p qirrali — shoir, tarixchi, muallim, vatanparvar","Qo'rqoq","Shuhratparast"],1),
makeQ("11. Asar uslubi qanday?",["Yumoristik","Tarixiy-biografik va hujjatli","Fantastik","Romantik"],1),
makeQ("12. Ibratning she'riy ijodida qaysi mavzu ustun?",["Tabiat tasviri","Vatanparvarlik, ma'rifat va milliy o'zlik","Sevgi lirikasi","Hajv"],1),
makeQ("13. Asarda sovet davri qanday aks ettiriladi?",["Ideallashtirib","Jabr va ta'qib davri sifatida yashirin ko'rsatiladi","Befarq","Maqtov bilan"],1),
makeQ("14. Ibrat xalq uchun qanday meros qoldirdi?",["Moddiy boylik","Ma'naviy meros — she'rlar, tarixiy asarlar va ma'rifat yo'li","Harbiy g'alaba","Diplomatik shartnomalar"],1),
makeQ("15. Asarning o'zbek adabiyotidagi ahamiyati?",["Ikkinchi darajali","Unutilgan jadid siymosini xalqqa qaytargan muhim asar"],1),
makeQ("16. Ibratning qaysi asari mashhur?",["Roman","Tarixiy va she'riy asarlari","Dramatik pьesa","Hikoyalar to'plami"],1),
makeQ("17. Asarda milliy o'zlik qanday ko'rsatiladi?",["Siyosiy bayonotlar","Qahramon hayoti va ijodi orqali tabiiy ko'rsatiladi","Diniy ibodatlar","Harbiy qahrmonlik"],1),
makeQ("18. Asar asosan kimga mo'ljallangan?",["Faqat tarixchilar","Milliy tarixni sevuvchi barcha o'quvchilar uchun","Faqat bolalar","Faqat ziyolilar"],1),
makeQ("19. Ibratning eng muhim xislati nima?",["Boylik","Bilimga chanqoqlik, fidokorlik va vatanparvarlik","Ayyorlik","Shuhratparastlik"],1),
makeQ("20. Asarda qaysi davr tasvirlanadi?",["Temuriylar davri","Jadidlik va sovet bosqini davri — XIX asr oxiri, XX asr boshlari","Mustaqillik yillari","Ikkinchi Jahon urushi"],1)
],
4:[
makeQ("1. 'Abdurauf Fitrat' asari kimning hayotini yoritadi?",["Abdulla Qodiriyning","Abdurauf Fitrat hayotini","Munavvar Qorining","Cho'lponning"],1),
makeQ("2. Fitrat qaysi faoliyat bilan mashhur?",["Harbiy sardor","Yozuvchi, dramaturg, davlat arbobi va jadid rahbari","Savdogar","Muhandis"],1),
makeQ("3. Bahodir Karimov bu asarda nima maqsad qilgan?",["Qahramonni tanqid qilish","Fitrat siymosini zamonaviy avlodga tanishtirish","Ko'ngilni ochish","Siyosiy targ'ibot"],1),
makeQ("4. Fitrat qaysi davrda ijod qilgan?",["XIX asr o'rtalari","XX asr boshlari — jadidlik va dastlabki sovet davri","Sovet davri oxiri","Mustaqillik davri"],1),
makeQ("5. Fitratning asosiy g'oyasi nima?",["Boylik va shuhrat","Milliy istiqlol, ma'rifat va isloh","Harbiy qudrat","Diniy hukmronlik"],1),
makeQ("6. Fitrat qaysi davlatda davlat arbobi bo'lgan?",["Chor Rossiyasi","Buxoro Xalq Sovet Respublikasi","O'zbekiston SSR","Qo'qon xonligi"],1),
makeQ("7. Fitratning fojiasi nimada?",["Kambag'allikda","1937-yilda Stalin repressiyasi davomida qatl etilganida","Sevgi alamida","Kasallikda"],1),
makeQ("8. Asar qaysi janrga mansub?",["Detektiv","Biografik-tarixiy qissa","She'riy doston","Hajviy asar"],1),
makeQ("9. Fitrat asarlarida qaysi til va uslub ishlatilgan?",["Ruscha","O'zbek va tojik tillarida, boy adabiy uslub","Arabcha","Inglizcha"],1),
makeQ("10. Asarda Fitrat obrazi qanday ko'rsatiladi?",["Manfaatparast","Ko'p qirrali shaxs — adib, siyosatchi, vatanparvar","Qo'rqoq","Shuhratparast"],1),
makeQ("11. Fitratning eng mashhur dramasi qaysi?",["Mehrobdan chayon","Abulfayzxon yoki Temur sog'inda","Navoiy","Shum bola"],1),
makeQ("12. Asarda sovet tuzumiga munosabat qanday?",["Maqtov","Fojiaviy natija orqali yashirin tanqid","Befarq","To'g'ridan-to'g'ri tanqid"],1),
makeQ("13. Fitrat xalq uchun qanday meros qoldirdi?",["Moddiy boylik","Milliy adabiyot, dramaturgiya va ma'rifat yo'li","Harbiy g'alaba","Diplomatik shartnomalar"],1),
makeQ("14. Asarning uslubi qanday?",["Yumoristik","Tarixiy-hujjatli va badiiy","Fantastik","Romantik"],1),
makeQ("15. Fitrat jadidlar harakatida qanday o'rin tutgan?",["Ikkinchi darajali","Yetakchi g'oyaviy va siyosiy arbob","Oddiy a'zo","Tanqidchi"],1),
makeQ("16. Asarda milliy ozodlik g'oyasi qanday ko'rsatiladi?",["Bevosita bayonot","Qahramon hayoti va kurashi orqali","Diniy ibodatlar","Harbiy sahnalar"],1),
makeQ("17. Fitrat qaysi shahar bilan bog'liq?",["Toshkent","Buxoro","Samarqand","Namangan"],1),
makeQ("18. Asarning o'zbek adabiyotidagi o'rni?",["Oddiy asar","Jadid adabiyoti tarixini boyitgan muhim biografik asar"],1),
makeQ("19. Fitrat nima sababli xalq qalbida yashaydi?",["Boylik","Milliy uyg'onishga qo'shgan ulkan hissasi","Harbiy g'alaba","Siyosiy muvaffaqiyatlar"],1),
makeQ("20. Asarda qaysi tarixiy davr markaziy o'rinni egallaydi?",["Temuriylar","Jadidlik va dastlabki sovet davri","Ikkinchi Jahon urushi","Mustaqillik yillari"],1)
],
5:[
makeQ("1. 'Abdulla Qodiriy' asari (Bahodir Karimov) nimani tasvirlaydi?",["Qodiriyning asarlarini tahlil","Abdulla Qodiriy hayoti va ijodini","Mehrobdan chayonning syujetini","Zamonaviy adabiyotni"],1),
makeQ("2. Abdulla Qodiriy o'zbek adabiyotida qanday o'rin tutadi?",["Ikkinchi darajali yozuvchi","O'zbek romanchiligining otasi","Faqat tarjimon","Sovet davri yozuvchisi"],1),
makeQ("3. Qodiriyning eng mashhur asari qaysi?",["Navoiy","Mehrobdan chayon","Shum bola","Kecha va kunduz"],1),
makeQ("4. Qodiriy qaysi yili qatl etilgan?",["1929","1938","1945","1952"],1),
makeQ("5. Bahodir Karimov asarida nima maqsad qilgan?",["Qodiriyni tanqid qilish","Ulug' yozuvchi hayotini va fojiasini yoritish","Ko'ngilni ochish","Siyosiy targ'ibot"],1),
makeQ("6. Qodiriy asarlarining asosiy xususiyati nima?",["Faqat sevgi mavzusi","Milliy tarix, an'ana va insoniy qadriyatlarni ulug'lash","Siyosiy targ'ibot","Harbiy tasvir"],1),
makeQ("7. Qodiriy qaysi davr hayotini asarlarida tasvirlagan?",["Temuriylar davri","XIX asr oxiri va XX asr boshlari o'zbek hayoti","Sovet davri","Mustaqillik yillari"],1),
makeQ("8. Asarda Qodiriy obrazi qanday ko'rsatiladi?",["Manfaatparast","Fidoyi va vatanparvar yozuvchi, millat ovozi","Qo'rqoq","Shuhratparast"],1),
makeQ("9. Qodiriyning ikkinchi mashhur romani qaysi?",["Bolalik","O'tkan kunlar","Navoiy","Shum bola"],1),
makeQ("10. Asarda sovet repressiyasi qanday aks ettirilgan?",["Maqtov bilan","Fojiaviy haqiqat sifatida — Qodiriyning qatli orqali","Befarq","Inkor etib"],1),
makeQ("11. Qodiriy o'z asarlarida qaysi g'oyani ilgari surgan?",["Boylik va shuhrat","Milliy uyg'onish, erkinlik va insoniy qadriyatlar","Harbiy qudrat","Diniy hukmronlik"],1),
makeQ("12. Asar qaysi janrga mansub?",["Detektiv","Biografik-tarixiy asar","She'riy doston","Hajviy"],1),
makeQ("13. Qodiriyning asarlari qaysi tilda yozilgan?",["Ruscha","O'zbek tilida","Arabcha","Forscha"],1),
makeQ("14. Asarda Qodiriy va zamon munosabati qanday?",["Uyg'un va tinch","Ziddiyatli — u tuzum tomonidan ezildi","Befarq","Ijobiy"],1),
makeQ("15. Qodiriyning xalq uchun qoldirgan merosi nima?",["Moddiy boylik","O'zbek klassik romanchiligining poydevori","Harbiy g'alaba","Diplomatik aloqalar"],1),
makeQ("16. Bahodir Karimov asari o'quvchiga nima beradi?",["Ko'ngil ochar","Milliy qahramon haqida chuqur bilim va g'urur","Qo'rqituv","Siyosiy ko'rsatma"],1),
makeQ("17. Qodiriy nima sababli xalq qalbida abadiy yashaydi?",["Boylik","O'zbek romanchiligini yaratgani va millat uchun jonini fido qilgani","Harbiy g'alaba","Siyosiy muvaffaqiyat"],1),
makeQ("18. Asar uslubi qanday?",["Yumoristik","Tarixiy-hujjatli va hayotiy","Fantastik","Romantik"],1),
makeQ("19. Asarning o'zbek adabiyotidagi ahamiyati?",["Oddiy asar","Klassik yozuvchi xotirasini tiklagan va ulug'lagan muhim asar"],1),
makeQ("20. Qodiriy qaysi laqab bilan mashhur?",["Milliy shoir","O'zbek romanchiligining otasi","Jadid arbobi","Xalq dramaturgі"],1)
],
6:[
makeQ("1. 'Abdulla Avloniy' asari (Olim Oltinbek) nimani yoritadi?",["Avloniyning she'rlarini tahlil","Abdulla Avloniy hayoti va jadid sifatidagi faoliyatini","Sovet davri adabiyotini","Zamonaviy pedagogikani"],1),
makeQ("2. Abdulla Avloniy qaysi faoliyat bilan mashhur?",["Harbiy sardor","Shoir, dramaturg, pedagog va jadid arbobi","Savdogar","Muhandis"],1),
makeQ("3. Avloniyning mashhur asari qaysi?",["Mehrobdan chayon","Turkiy guliston yoxud axloq","Navoiy","Shum bola"],1),
makeQ("4. Avloniy qaysi davrda ijod qilgan?",["XIX asr o'rtalari","XX asr boshlari — jadidlik davri","Sovet davri oxiri","Mustaqillik davri"],1),
makeQ("5. Asarning asosiy mavzusi nima?",["Sevgi","Ma'rifat, axloq va milliy uyg'onish yo'lida xizmat","Harbiy sarguzasht","Boylik"],1),
makeQ("6. Avloniyning ta'lim sohasidagi xizmati nimada?",["Harbiy maktab ochdi","Yangi usul maktablari ochib, milliy ta'limni isloh qildi","Savdo maktabi ochdi","Din maktabi ochdi"],1),
makeQ("7. Olim Oltinbek asarida nima maqsad qilgan?",["Qahramonni tanqid qilish","Avloniy siymosini zamonaviy avlodga tanishtirish","Ko'ngilni ochish","Siyosiy targ'ibot"],1),
makeQ("8. Avloniyning fojiasi nimada?",["Kambag'allikda","Sovet tuzumi tomonidan ta'qib va quvg'in qilinganida","Sevgi alamida","Kasallikda"],1),
makeQ("9. 'Turkiy guliston yoxud axloq' asarining asosiy g'oyasi nima?",["Boylik","Axloqiy tarbiya va milliy ma'rifat","Harbiy qudrat","Diniy hukmronlik"],1),
makeQ("10. Avloniy qaysi shahar bilan bog'liq?",["Samarqand","Toshkent","Buxoro","Namangan"],1),
makeQ("11. Asarda Avloniy obrazi qanday ko'rsatiladi?",["Manfaatparast","Ko'p qirrali shaxs — adib, muallim, vatanparvar","Qo'rqoq","Shuhratparast"],1),
makeQ("12. Asar qaysi janrga mansub?",["Detektiv","Biografik-tarixiy asar","She'riy doston","Hajviy"],1),
makeQ("13. Avloniy xalq uchun qanday meros qoldirdi?",["Moddiy boylik","Milliy adabiyot, pedagogika va ma'rifat yo'li","Harbiy g'alaba","Diplomatik aloqalar"],1),
makeQ("14. Asarda milliy uyg'onish g'oyasi qanday ko'rsatiladi?",["Siyosiy bayonotlar","Avloniy hayoti va ijodi orqali tabiiy","Diniy ibodatlar","Harbiy sahnalar"],1),
makeQ("15. Avloniy dramaturgiyasining asosiy maqsadi?",["Ko'ngil ochish","Jamiyatni axloqiy tarbiyalash va isloh qilish","Siyosiy targ'ibot","Shaxsiy shuhrat"],1),
makeQ("16. Asarning uslubi qanday?",["Yumoristik","Tarixiy-hujjatli va badiiy","Fantastik","Romantik"],1),
makeQ("17. Avloniy nima sababli xalq qalbida yashaydi?",["Boylik","Milliy ta'lim va axloqqa qo'shgan ulkan hissasi","Harbiy g'alaba","Siyosiy muvaffaqiyat"],1),
makeQ("18. Asarning o'zbek adabiyotidagi o'rni?",["Oddiy asar","Jadid adabiyoti tarixini boyitgan muhim biografik asar"],1),
makeQ("19. Avloniyning asarlarida qaysi qadriyatlar ustun?",["Moddiy qadriyatlar","Axloqiy tarbiya, vatanparvarlik va ma'rifat","Harbiy qahrmonlik","Diniy fanatizm"],1),
makeQ("20. Asarda qaysi tarixiy davr markaziy o'rinni egallaydi?",["Temuriylar","Jadidlik va sovet bosqini davri","Ikkinchi Jahon urushi","Mustaqillik yillari"],1)
],
7:[
makeQ("1. 'Abdulhamid Cho'lpon' asari (Dilmurod Quronov) nimani yoritadi?",["Cho'lpon she'rlarini tahlil","Cho'lpon hayoti, ijodi va fojiasini","Sovet davri adabiyotini","Zamonaviy she'riyatni"],1),
makeQ("2. Cho'lpon qaysi faoliyat bilan mashhur?",["Harbiy sardor","O'zbek she'riyati va dramaturgiysining ulug' vakili — jadid","Savdogar","Muhandis"],1),
makeQ("3. Cho'lponning mashhur romani qaysi?",["Mehrobdan chayon","Kecha va kunduz","Navoiy","Shum bola"],1),
makeQ("4. Cho'lpon qaysi yili qatl etilgan?",["1929","1938","1945","1952"],1),
makeQ("5. Dilmurod Quronov asarida nima maqsad qilgan?",["Cho'lponni tanqid qilish","Cho'lpon siymosini va fojiasini yoritish","Ko'ngilni ochish","Siyosiy targ'ibot"],1),
makeQ("6. Cho'lponning she'riyatida qaysi mavzu ustun?",["Tabiat tasviri","Ozodlik, milliy uyg'onish va sevgi","Harbiy tasvir","Yumoristic mavzu"],1),
makeQ("7. 'Kecha va kunduz' romanining asosiy mavzusi?",["Harbiy sarguzasht","Mustamlaka davridagi o'zbek ayolining fojiaviy taqdiri","Boylik orttirishning yo'llari","Sovet hayotini maqtash"],1),
makeQ("8. Cho'lpon qaysi davrda ijod qilgan?",["XIX asr o'rtalari","XX asr boshlari — jadidlik va dastlabki sovet davri","Sovet davri oxiri","Mustaqillik davri"],1),
makeQ("9. Asarda Cho'lpon obrazi qanday ko'rsatiladi?",["Manfaatparast","Ko'p qirrali shaxs — shoir, dramaturg, tarjimon, vatanparvar","Qo'rqoq","Shuhratparast"],1),
makeQ("10. Asarda sovet repressiyasi qanday aks ettirilgan?",["Maqtov","Fojiaviy haqiqat — Cho'lponning qatli orqali","Befarq","Inkor etib"],1),
makeQ("11. Cho'lponning she'rlarida qaysi his ustun?",["Quvonch","Ozodlikka intilish va sog'inch","G'azab","Befarqlik"],1),
makeQ("12. Asar qaysi janrga mansub?",["Detektiv","Biografik-adabiy tadqiqot","She'riy doston","Hajviy"],1),
makeQ("13. Cho'lpon xalq uchun qanday meros qoldirdi?",["Moddiy boylik","O'zbek she'riyati va dramaturgiysining oltin sahifalari","Harbiy g'alaba","Diplomatik aloqalar"],1),
makeQ("14. Asarning o'zbek adabiyotidagi ahamiyati?",["Oddiy asar","Unutilgan ulug' shoir xotirasini tiklagan va ulug'lagan asar"],1),
makeQ("15. Cho'lpon nima sababli xalq qalbida abadiy?",["Boylik","O'zbek she'riyatini yangi bosqichga olib chiqqani","Harbiy g'alaba","Siyosiy muvaffaqiyat"],1),
makeQ("16. Asarning uslubi qanday?",["Yumoristik","Ilmiy-badiiy va tarixiy-hujjatli","Fantastik","Romantik"],1),
makeQ("17. Cho'lponning qaysi asari o'zbek dramaturgiyasida muhim?",["Mehrobdan chayon","Yorqinoy dramasi","Navoiy","Shum bola"],1),
makeQ("18. Asarda jadidlik va sovet tuzumi munosabati qanday?",["Ijobiy","Ziddiyatli va fojiaviy — jadidlar quvg'in qilindi","Befarq","Maqtov"],1),
makeQ("19. Cho'lponning asarlarida qaysi qadriyatlar ustun?",["Moddiy qadriyatlar","Erkinlik, milliy uyg'onish va insoniy qadriyatlar","Harbiy qahrmonlik","Diniy fanatizm"],1),
makeQ("20. Asarda qaysi tarixiy davr markaziy o'rinni egallaydi?",["Temuriylar","Jadidlik davri va sovet repressiyasi","Ikkinchi Jahon urushi","Mustaqillik yillari"],1)
],
8:[
makeQ("1. 'Mahmudxo'ja Behbudiy' asari kimning hayotini yoritadi?",["Abdulla Qodiriyning","Mahmudxo'ja Behbudiy hayotini","Munavvar Qorining","Fitratning"],1),
makeQ("2. Behbudiy qaysi faoliyat bilan mashhur?",["Harbiy sardor","Dramaturg, ma'rifatchi va jadid harakatining asoschisi","Savdogar","Muhandis"],1),
makeQ("3. Behbudiyning mashhur dramasi qaysi?",["Mehrobdan chayon","Padarkush","Navoiy","Shum bola"],1),
makeQ("4. Behbudiy qaysi shahar bilan bog'liq?",["Toshkent","Samarqand","Buxoro","Namangan"],1),
makeQ("5. 'Padarkush' dramasining asosiy g'oyasi nima?",["Boylik","Ilmsizlik — ota-onani o'ldirishga olib keluvchi kuch","Harbiy qudrat","Diniy hukmronlik"],1),
makeQ("6. Behbudiy qanday o'ldirilgan?",["Kasallikdan","Amir Olimxon buyrug'i bilan o'ldirilgan","Urushda halok bo'lgan","Qatl etilgan"],1),
makeQ("7. Zaynobiddin Abdurashidov asarida nima maqsad qilgan?",["Qahramonni tanqid qilish","Behbudiy siymosini va xizmatlarini yoritish","Ko'ngilni ochish","Siyosiy targ'ibot"],1),
makeQ("8. Behbudiyning asosiy g'oyasi nima?",["Boylik va shuhrat","Ma'rifat, isloh va milliy uyg'onish","Harbiy qudrat","Diniy hukmronlik"],1),
makeQ("9. Asar qaysi janrga mansub?",["Detektiv","Biografik-tarixiy qissa","She'riy doston","Hajviy"],1),
makeQ("10. Behbudiy jadidlar harakatida qanday o'rin tutgan?",["Ikkinchi darajali","Asoschisi va yetakchi arbobi","Oddiy a'zo","Tanqidchi"],1),
makeQ("11. Behbudiy qaysi davrda faoliyat ko'rsatgan?",["XIX asr o'rtalari","XX asr boshlari — jadidlik davri","Sovet davri oxiri","Mustaqillik davri"],1),
makeQ("12. Asarda Behbudiy obrazi qanday ko'rsatiladi?",["Manfaatparast","Fidoyi va vatanparvar ma'rifatchi","Qo'rqoq","Shuhratparast"],1),
makeQ("13. Behbudiyning xalq uchun merosi nima?",["Moddiy boylik","O'zbek teatri va ma'rifatiga asos solishi","Harbiy g'alaba","Diplomatik aloqalar"],1),
makeQ("14. Asarning uslubi qanday?",["Yumoristik","Tarixiy-hujjatli va badiiy","Fantastik","Romantik"],1),
makeQ("15. Asarning o'zbek adabiyotidagi o'rni?",["Oddiy asar","Jadid adabiyoti tarixini boyitgan muhim biografik asar"],1),
makeQ("16. Behbudiy nima sababli xalq qalbida yashaydi?",["Boylik","O'zbek teatri va jadid harakatiga qo'shgan ulkan hissasi","Harbiy g'alaba","Siyosiy muvaffaqiyat"],1),
makeQ("17. Asarda milliy uyg'onish g'oyasi qanday ko'rsatiladi?",["Siyosiy bayonotlar","Behbudiy hayoti va kurashi orqali tabiiy","Diniy ibodatlar","Harbiy sahnalar"],1),
makeQ("18. Behbudiy qaysi sohada birinchi qadam qo'ygan?",["Harbiy soha","O'zbek professional teatrini yaratish","Savdo-sotiq","Din sohasida islohotlar"],1),
makeQ("19. Asarda Behbudiyning fojiali o'limi qanday yoritiladi?",["Maqtov bilan","Millat yo'lidagi qurbonlik sifatida fojiaviy","Befarq","Inkor etib"],1),
makeQ("20. Asarda qaysi tarixiy davr markaziy o'rinni egallaydi?",["Temuriylar","Jadidlik davri va amir hukmronligi","Ikkinchi Jahon urushi","Mustaqillik yillari"],1)
],
9:[
makeQ("1. 'Avlodlar dovoni' romanining bosh qahramoni kim?",["Hamid","Yorqinoy","Saidakbar","Kamoliddin"],2),
makeQ("2. Romanda asosiy ziddiyat nimadan iborat?",["Sevgi va nafrat","Ikki avlod — ota va o'g'il o'rtasidagi tushunmovchilik va hayot yo'li","Boylik va qashshoqlik","Urush va tinchlik"],1),
makeQ("3. 'Dovon' obrazi romanda nimani anglatadi?",["Tog' o'tkazgichi","Hayotdagi sinovlar va avlodlar orasidagi ko'prik","Tabiat manzarasi","Harbiy istehkom"],1),
makeQ("4. Pirimqul Qodirov romanida qaysi davrni tasvirlaydi?",["Temuriylar davri","Sovet davridan mustaqillikka o'tish davri","Jadidlik davri","XIX asr"],1),
makeQ("5. Asarning asosiy mavzusi nima?",["Sevgi","Avlodlar bog'liqligi, milliy o'zlik va tarixiy xotira","Harbiy sarguzasht","Boylik"],1),
makeQ("6. Saidakbar qanday qahramon?",["Manfaatparast","O'z ildizlarini izlaydigan, milliy o'zlikni anglashga intilgan inson","Qo'rqoq","Shuhratparast"],1),
makeQ("7. Romanda tarix va hozirgi zamon qanday bog'liq?",["Bog'liq emas","Avlodlar xotirasi orqali o'tmish hozirga ko'prik bo'lib xizmat qiladi","Faqat tarix tasvirlanadi","Faqat hozirgi zamon"],1),
makeQ("8. Asarning uslubi qanday?",["Yumoristik","Epik-falsafiy, tarixiy va lirik elementlar birikmasida","Detektiv","Romantik"],1),
makeQ("9. Romanda o'zbek milliy qadriyatlari qanday ko'rsatiladi?",["Tanqid ostida","Avlodlar xotirasi va an'analar orqali ulug'lanadi","Befarq","Salbiy"],1),
makeQ("10. Asardagi 'dovon' metaforasi nimani ifodalaydi?",["Oddiy tog' yo'li","Hayotdagi qiyinchiliklar va avlodlar o'rtasidagi sinovli ko'prik","Harbiy istehkom","Chegaraviy nuqta"],1),
makeQ("11. Pirimqul Qodirov o'zbek adabiyotida qanday o'rin tutadi?",["Ikkinchi darajali","Tarixiy roman janrining yirik vakili","Faqat tarjimon","Sovet davri yozuvchisi"],1),
makeQ("12. Romanda ota va o'g'il munosabati qanday?",["Ideal va muammosiz","Murakkab, lekin sevgi va tushunishga intilish asosida","Dushmanona","Befarq"],1),
makeQ("13. Asarda milliy tarix qanday rol o'ynaydi?",["Ikkinchi darajali","Asarning poydevori — o'zlikni anglashning manbai","Ahamiyatsiz","Faqat fon"],1),
makeQ("14. Romanning finali qanday kayfiyat bilan tugaydi?",["Pessimistik","Umid va avlodlar zanjirining davom etishi hissi bilan","Dramatik fojia","Shod-xurramlik"],1),
makeQ("15. Asarda qaysi milliy qadriyat eng muhim sifatida ko'rsatiladi?",["Boylik","Milliy xotira va avlodlar bog'liqligi","Harbiy qudrat","Diniy e'tiqod"],1),
makeQ("16. Roman qaysi janrga mansub?",["Qissa","Tarixiy-falsafiy roman","Hikoyalar to'plami","Dramatik doston"],1),
makeQ("17. Asarda O'zbekiston tarixi qanday aks ettiriladi?",["Ideallashtirib","Voqelikka yaqin, murakkab va ko'p qatlamli tarzda","Salbiy","Ahamiyatsiz"],1),
makeQ("18. Saidakbar o'z ildizlarini topganida qanday his qiladi?",["Befarq","O'zligini anglash va milliy g'ururni his qiladi","Xafa bo'ladi","Qo'rqadi"],1),
makeQ("19. Romanning asosiy xulosasi nima?",["Boylik muhim","Avlodlar zanjiri uzilmasligi kerak — o'zlikni unutmaslik shart","Shahrda yasha","Siyosatga qo'shil"],1),
makeQ("20. Asar o'zbek adabiyotida qanday o'rin tutadi?",["Oddiy asar","Tarixiy roman janrining yirik namunasi — milliy o'zlikni ulug'lagan asar"],1)
],
10:[
makeQ("1. 'Aqchagul' asarining bosh qahramoni kim?",["Hamid","Aqchagul","Mansur","Karim"],1),
makeQ("2. Asarning asosiy mavzusi nima?",["Siyosiy kurash","Ayol taqdiri, muhabbat va milliy an'analar","Harbiy sarguzasht","Boylik"],1),
makeQ("3. Aqchagul qanday obraz?",["Manfaatparast","Kuchli, fidoyi va o'z taqdiri uchun kurashuvchi ayol","Zaif va itoatkor","Shuhratparast"],1),
makeQ("4. Murodboy Nizanov asarida qaysi davr hayotini tasvirlaydi?",["Temuriylar davri","XX asr o'zbek qishloq hayoti","Jadidlik davri","Mustaqillik yillari"],1),
makeQ("5. Asardagi sevgi qanday his sifatida ko'rsatiladi?",["Jismoniy tortishish","Sof, chuqur va hayot mazmunini beruvchi his","Muammoli faqat","Ahamiyatsiz"],1),
makeQ("6. Asarda an'anaviy va yangi hayot o'rtasidagi ziddiyat qanday?",["Yo'q","Aqchagul taqdiri orqali keskin va hayotiy ko'rsatiladi","Ahamiyatsiz","Ijobiy"],1),
makeQ("7. Asarning uslubi qanday?",["Yumoristik","Lirik-psixologik va hayotiy","Detektiv","Fantastik"],1),
makeQ("8. Asarda qishloq hayoti qanday tasvirlanadi?",["Ideallashtirib","Haqiqiy va murakkabliklari bilan birga samimiy","Salbiy","Ahamiyatsiz"],1),
makeQ("9. Aqchagulning hayotdagi asosiy qidiruvi nima?",["Boylik","Sevgi, erkinlik va insoniy baxt","Shuhrat","Siyosiy ta'sir"],1),
makeQ("10. Asarda ayol obrazi qanday talqin etiladi?",["Zaif va itoatkor","Kuchli, his-tuyg'uli va o'z taqdiri uchun kurashuvchi","Ikkinchi darajali","Salbiy"],1),
makeQ("11. Asarning finali qanday kayfiyat bilan tugaydi?",["Shod-xurramlik","Og'riq va umid aralash lirik kayfiyat","Pesimistik","Hajviy"],1),
makeQ("12. Asarda tabiat tasviri qanday rol o'ynaydi?",["Faqat bezak","Qahramon ichki holatini aks ettiruvchi muhim unsur","Ahamiyatsiz","Vaqtni belgilash"],1),
makeQ("13. Aqchagulning atrofidagilar bilan munosabati qanday?",["Dushmanona","Murakkab, lekin sevgi va mehr asosida","Befarq","Rasmiy"],1),
makeQ("14. Asarda milliy urf-odatlar qanday ko'rsatiladi?",["Tanqid ostida","Hayotiy haqiqat sifatida, lekin insoniylik saqlanib","Ideallashtirib","Salbiy"],1),
makeQ("15. Asarning bosh g'oyasi nima?",["Boylikka intil","Insoniy baxt va erkinlik — eng oliy qadriyat","Shahrda yasha","Siyosatga qo'shil"],1),
makeQ("16. Asarning o'zbek adabiyotidagi o'rni?",["Oddiy asar","Ayol taqdirini kuchli lirik-psixologik uslubda yoritgan asar"],1),
makeQ("17. Aqchagulning eng muhim xislati nima?",["Boylik","Kuchlilik, sadoqat va hayotga muhabbat","Ayyorlik","Shuhratparastlik"],1),
makeQ("18. Asardagi eng kuchli badiiy obraz nima?",["Qishloq tasviri","Aqchagulning o'zi — kuchli va his-tuyg'uli ayol obrazi","Xaroba uy","Suv"],1),
makeQ("19. Asarda vaqt qanday ishlaydi?",["Faqat hozirgi vaqt","Hozirgi va o'tgan vaqt o'zaro bog'liq tarzda","Faqat o'tgan vaqt","Kelajak"],1),
makeQ("20. Murodboy Nizanov asarida qaysi ijtimoiy muammo ko'tariladi?",["Iqtisodiy muammo","Ayollarning ijtimoiy ahvoli va erkinlik masalasi","Siyosiy kurash","Ekologik muammo"],1)
]
};

// ID 11-100 uchun umumiy savollar generatori
var genericQs = function(bookTitle, author) {
  return [
    makeQ("1. '"+bookTitle+"' asarining asosiy mavzusi nima?",["Siyosiy kurash","Insoniy qadriyatlar, taqdiri va ichki izlanish","Harbiy sarguzasht","Boylik"],1),
    makeQ("2. Asarning janri qaysi?",["Detektiv","Badiiy adabiyot — roman yoki qissa","She'riy doston","Ilmiy asar"],1),
    makeQ("3. Muallif "+author+" bu asarda nima maqsad qilgan?",["Qahramonni tanqid qilish","Insoniy va milliy qadriyatlarni yoritish","Ko'ngilni ochish","Siyosiy targ'ibot"],1),
    makeQ("4. Asardagi bosh qahramon qanday insoniylik namunasi?",["Manfaatparast","Fidoyi, vijdonli va insonparvar","Qo'rqoq","Shuhratparast"],1),
    makeQ("5. Asarda asosiy ziddiyat nimadan iborat?",["Insonlar va tabiat","Shaxsiy qadriyatlar va tashqi muhit bosimi o'rtasida","Ijtimoiy sinflar","Milliy mojarolar"],1),
    makeQ("6. Asarning uslubi qanday?",["Yumoristik","Psixologik-badiiy va hayotiy","Detektiv","Fantastik"],1),
    makeQ("7. Asarda jamiyat qanday tasvirlanadi?",["Ideal va adolatli","Murakkab, ziddiyatli va haqiqiy","Tinch va baxtli","Befarq"],1),
    makeQ("8. Bosh qahramon hayotdagi asosiy qidiruvi nima?",["Boylik","Ma'no, insoniy qadriyatlar va o'z-o'zini anglash","Shuhrat","Siyosiy ta'sir"],1),
    makeQ("9. Asardagi sevgi yoki do'stlik qanday his sifatida ko'rsatiladi?",["Jismoniy tortishish","Sof va insonni uyg'otuvchi chuqur his","Muammoli faqat","Ahamiyatsiz"],1),
    makeQ("10. Asarning finali qanday kayfiyat bilan tugaydi?",["Shod-xurramlik","O'ylantiruvchi, umid va haqiqat aralash kayfiyat","Dramatik fojia","Hajviy"],1),
    makeQ("11. Asarda milliy qadriyatlar qanday ko'rsatiladi?",["Tanqid ostida","Tabiiy va hayotiy tarzda ulug'lanadi","Befarq","Salbiy"],1),
    makeQ("12. Asarning kompozitsiyasi qanday?",["Bir chiziqliy oddiy","Murakkab, turli qatlamlar va vaqt o'tishini o'z ichiga olgan","Detektiv tuzilma","Parallel syujetlar"],1),
    makeQ("13. Qahramon ichki dunyosi qanday ko'rsatiladi?",["Tashqi ta'rif orqali","Ichki monolog, xotira va kechinmalar orqali chuqur","Muallif izohi bilan","Boshqa qahramonlar gapi orqali"],1),
    makeQ("14. Asardagi tabiat tasviri qanday funktsiya bajaradi?",["Faqat bezak","Qahramon ichki holatini aks ettiradi","Vaqtni belgilaydi","Ahamiyatsiz"],1),
    makeQ("15. Asarning bosh g'oyasi nima?",["Boylikka intil","Insoniylik, vijdon va haqiqiy qadriyatlar — eng oliy boylik","Shahrda yasha","Harbiy qudrat"],1),
    makeQ("16. Asarda ikkinchi darajali qahramonlar qanday vazifani o'taydi?",["Ahamiyatsiz","Bosh qahramon ichki dunyosini ochishga xizmat qiladi","Hajviy vazifa","Syujetni tezlashtiradi"],1),
    makeQ("17. Asar o'quvchiga qanday ta'sir ko'rsatadi?",["Qo'rqitadi","O'ylantiradi, hayot haqida chuqur fikrlashga undaydi","Faqat ko'ngilni ochadi","Siyosiy fikrlashga undaydi"],1),
    makeQ("18. Asardagi eng kuchli badiiy unsur nima?",["Shunchaki syujet","Psixologik chuqurlik va insoniy his-tuyg'ularning to'g'ri tasviri","Tarixiy faktlar","Hajviy sahnalar"],1),
    makeQ("19. Asar o'zbek adabiyotida qanday o'rin tutadi?",["Oddiy asar","O'zbek badiiy adabiyotining muhim namunasi"],1),
    makeQ("20. Asarning asosiy xulosasi nima?",["Boylik muhim","Insoniylik, vijdon va ma'naviy qadriyatlar — haqiqiy boylik","Kuch hukmron","Omad muhim"],1)
  ];
};

// 11-100 kitoblar uchun savollar
for(var i=10; i<BOOKS.length; i++){
  if(!TESTS[BOOKS[i].id]){
    TESTS[BOOKS[i].id] = genericQs(BOOKS[i].t, BOOKS[i].a);
  }
}
